version: '3'
services:
  postgresql:
    image: postgres
    container_name: basic-postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin
      - POSTGRES_DB=taskmate
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgresql:/var/lib/postgresql/data
  # redis:
  #   image: redis
  #   ports:
  #     - '6379:6379'
  taskmate:
    image: taskmate
    ports:
      - '5001:5001'
    volumes:
      - '../web:/run/web'
      - '../migrations:/run/migrations'
    environment:
      - SECRET_KEY=test
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:Admin@postgresql:5432/taskmate
      - DATABASE_HOST=postgresql
      - DATABASE_PORT=5432
      # - CELERY_RESULT_BACKEND=redis://redis:6379
      # - CELERY_BROKER_URL=redis://redis:6379
    depends_on:
      - postgresql
      # - redis