"""empty message

Revision ID: 3d7e26e42e9b
Revises: 2a1efa67bc4c
Create Date: 2023-06-17 08:48:09.774007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7e26e42e9b'
down_revision = '2a1efa67bc4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('task_comment', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_comment', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('created',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###
